stages:
  preprocess_data:
    cmd: python src/preprocess.py data/data.csv output/train_data.csv output/test_data.csv params.yaml
    deps:
      - src/preprocess.py
      - data/data.csv
      - params.yaml
    outs:
      - output/train_data.csv
      - output/test_data.csv