stages:
  preprocess_data:
    cmd: python .\src\preprocess.py data/data.csv output/cleaned_data.csv params.yaml
    deps:
    - .\data\data.csv
    - .\params.yaml
    - .\src\preprocess.py
    outs:
    - output/cleaned_data.csv
