stages:
  preprocess_data:
    cmd: python src/preprocess.py data/data.csv output/train_data.csv output/test_data.csv
      params.yaml
    deps:
    - src/preprocess.py
    - data/data.csv
    - params.yaml
    outs:
    - output/train_data.csv
    - output/test_data.csv
  train_models:
    cmd: python src/train.py output/train_data.csv output/test_data.csv params.yaml
      models/best_model.joblib
    deps:
    - output/test_data.csv
    - output/train_data.csv
    - params.yaml
    - src/train.py
    outs:
    - models/best_model.joblib
  optimize_models:
    cmd: python src/optimization_and_training.py output/train_data.csv output/test_data.csv
      params.yaml models/best_optimized_model.joblib
    deps:
    - output/test_data.csv
    - output/train_data.csv
    - params.yaml
    - src/optimization_and_training.py
    outs:
    - models/best_optimized_model.joblib
  interpret_results:
    cmd: python src/result_interpretation.py output/test_data.csv params.yaml models/best_optimized_model.joblib
      interpretation/results.csv
    deps:
    - models/best_optimized_model.joblib
    - output/test_data.csv
    - params.yaml
    - src/result_interpretation.py
    outs:
    - interpretation/results.csv
