train:
  test_size: 0.2
  random_state: 42
  alpha: 0.1

preprocessing:
  target: price
  features: [area, bedrooms, bathrooms, stories, parking]

models:
  linear_regression:
    type: "LinearRegression"
  random_forest:
    type: "RandomForestRegressor"
    n_estimators: 100
    max_depth: 10
  gradient_boosting:
    type: "GradientBoostingRegressor"
    n_estimators: 100
    learning_rate: 0.1
